export const PLAYER_SHEETS = {
  "human-fighter": {
    name: "Human Fighter",
    armorClass: 17,
    maxHp: 28,
    initiativeBonus: 1,
    speed: 30,
    attackProfiles: [
      { key: "longsword", name: "Longsword", actionType: "attack", attackBonus: 5, damageFormula: "1d8+3", damageType: "slashing", rangeFeet: 5, targetSide: "enemy" },
      { key: "handaxe", name: "Handaxe", actionType: "attack", attackBonus: 5, damageFormula: "1d6+3", damageType: "slashing", rangeFeet: 20, targetSide: "enemy" },
    ],
    spellProfiles: [
      { key: "second-wind", name: "Second Wind", actionType: "castSpell", resolutionMode: "healSelf", healFormula: "1d10+3", resourceKey: "secondWind", targetSide: "self" },
      { key: "action-surge", name: "Action Surge", actionType: "castSpell", resolutionMode: "buff", resourceKey: "actionSurge", targetSide: "self" },
    ],
    resources: { secondWind: { usesRemaining: 1, maxUses: 1 }, actionSurge: { usesRemaining: 1, maxUses: 1 }, spellSlots: {}, sorceryPoints: 0 },
    savingThrows: { str: 4, dex: 1, con: 4, int: 0, wis: 1, cha: 0 },
    resistances: [],
  },
  "dwarf-cleric": {
    name: "Dwarf Cleric",
    armorClass: 18,
    maxHp: 24,
    initiativeBonus: 0,
    speed: 25,
    attackProfiles: [{ key: "mace", name: "Mace", actionType: "attack", attackBonus: 5, damageFormula: "1d6+3", damageType: "bludgeoning", rangeFeet: 5, targetSide: "enemy" }],
    spellProfiles: [
      { key: "sacred-flame", name: "Sacred Flame", actionType: "castSpell", resolutionMode: "saveDamage", saveAbility: "dex", saveDc: 13, damageFormula: "1d8+3", damageType: "radiant", rangeFeet: 60, targetSide: "enemy" },
      { key: "healing-word", name: "Healing Word", actionType: "castSpell", resolutionMode: "heal", healFormula: "1d4+3", slotLevel: 1, rangeFeet: 60, targetSide: "ally" },
      { key: "shield-of-faith", name: "Shield Of Faith", actionType: "castSpell", resolutionMode: "buff", slotLevel: 1, concentration: true, buffCondition: "shield-of-faith", targetSide: "ally" },
    ],
    resources: { secondWind: { usesRemaining: 0, maxUses: 0 }, actionSurge: { usesRemaining: 0, maxUses: 0 }, spellSlots: { 1: 4, 2: 2 }, sorceryPoints: 0 },
    savingThrows: { str: 3, dex: 0, con: 3, int: 0, wis: 4, cha: 2 },
    resistances: ["poison"],
  },
  "elf-rogue": {
    name: "Elf Rogue",
    armorClass: 14,
    maxHp: 24,
    initiativeBonus: 4,
    speed: 30,
    attackProfiles: [
      { key: "rapier", name: "Rapier", actionType: "attack", attackBonus: 6, damageFormula: "1d8+4", damageType: "piercing", rangeFeet: 5, targetSide: "enemy" },
      { key: "shortbow", name: "Shortbow", actionType: "attack", attackBonus: 6, damageFormula: "1d6+4", damageType: "piercing", rangeFeet: 80, targetSide: "enemy" },
    ],
    spellProfiles: [{ key: "cunning-action", name: "Cunning Action", actionType: "move", resolutionMode: "move", targetSide: "self" }],
    resources: { secondWind: { usesRemaining: 0, maxUses: 0 }, actionSurge: { usesRemaining: 0, maxUses: 0 }, spellSlots: {}, sorceryPoints: 0 },
    savingThrows: { str: 0, dex: 6, con: 1, int: 2, wis: 1, cha: 0 },
    resistances: [],
  },
  "tiefling-sorcerer": {
    name: "Tiefling Sorcerer",
    armorClass: 13,
    maxHp: 21,
    initiativeBonus: 2,
    speed: 30,
    attackProfiles: [{ key: "dagger", name: "Dagger", actionType: "attack", attackBonus: 4, damageFormula: "1d4+2", damageType: "piercing", rangeFeet: 5, targetSide: "enemy" }],
    spellProfiles: [
      { key: "fire-bolt", name: "Fire Bolt", actionType: "castSpell", resolutionMode: "attack", attackBonus: 5, damageFormula: "1d10+3", damageType: "fire", rangeFeet: 120, targetSide: "enemy" },
      { key: "burning-hands", name: "Burning Hands", actionType: "castSpell", resolutionMode: "saveDamage", saveAbility: "dex", saveDc: 13, damageFormula: "3d6", damageType: "fire", slotLevel: 1, rangeFeet: 15, halfOnSave: true, targetSide: "enemy" },
    ],
    resources: { secondWind: { usesRemaining: 0, maxUses: 0 }, actionSurge: { usesRemaining: 0, maxUses: 0 }, spellSlots: { 1: 4, 2: 2 }, sorceryPoints: 3 },
    savingThrows: { str: 0, dex: 2, con: 1, int: 1, wis: 1, cha: 5 },
    resistances: ["fire"],
  },
};

export const ENEMY_TEMPLATES = {
  scavenger: {
    name: "Ashen Scavenger",
    armorClass: 12,
    maxHp: 9,
    initiativeBonus: 2,
    speed: 30,
    attackProfiles: [{ key: "scrap-blade", name: "Scrap Blade", actionType: "attack", attackBonus: 3, damageFormula: "1d6+1", damageType: "slashing", rangeFeet: 5, targetSide: "party" }],
    spellProfiles: [],
    resources: { spellSlots: {}, secondWind: { usesRemaining: 0, maxUses: 0 }, actionSurge: { usesRemaining: 0, maxUses: 0 } },
    savingThrows: { str: 1, dex: 2, con: 1, int: -1, wis: 0, cha: -1 },
    resistances: [],
  },
  brute: {
    name: "Bridge Brute",
    armorClass: 13,
    maxHp: 16,
    initiativeBonus: 0,
    speed: 25,
    attackProfiles: [{ key: "crushing-hammer", name: "Crushing Hammer", actionType: "attack", attackBonus: 4, damageFormula: "1d8+2", damageType: "bludgeoning", rangeFeet: 5, targetSide: "party" }],
    spellProfiles: [],
    resources: { spellSlots: {}, secondWind: { usesRemaining: 0, maxUses: 0 }, actionSurge: { usesRemaining: 0, maxUses: 0 } },
    savingThrows: { str: 3, dex: 0, con: 2, int: -1, wis: 0, cha: -1 },
    resistances: [],
  },
  archer: {
    name: "Rain Arrow",
    armorClass: 12,
    maxHp: 11,
    initiativeBonus: 3,
    speed: 30,
    attackProfiles: [{ key: "hunters-shot", name: "Hunter's Shot", actionType: "attack", attackBonus: 4, damageFormula: "1d6+1", damageType: "piercing", rangeFeet: 80, targetSide: "party" }],
    spellProfiles: [],
    resources: { spellSlots: {}, secondWind: { usesRemaining: 0, maxUses: 0 }, actionSurge: { usesRemaining: 0, maxUses: 0 } },
    savingThrows: { str: 0, dex: 4, con: 1, int: 0, wis: 1, cha: -1 },
    resistances: [],
  },
};
